<?php

namespace Database\Seeders;

use App\Models\Habilidade;
use Illuminate\Database\Seeder;

class HabilidadeSeeder extends Seeder
{
    public function run()
    {
        $habilidades = [
            'Assembly',
            'Ada',
            'ALGOL',
            'APL',
            'AutoHotkey',
            'BASIC',
            'Bash',
            'C',
            'C#',
            'C++',
            'Clojure',
            'COBOL',
            'Crystal',
            'D',
            'Dart',
            'Delphi',
            'Elixir',
            'Erlang',
            'F#',
            'Fortran',
            'Go',
            'Groovy',
            'Haskell',
            'Java',
            'JavaScript',
            'Julia',
            'Kotlin',
            'Lisp',
            'Lua',
            'MATLAB',
            'Nim',
            'Objective-C',
            'OCaml',
            'Pascal',
            'Perl',
            'PHP',
            'PowerShell',
            'Prolog',
            'Python',
            'R',
            'Racket',
            'Ruby',
            'Rust',
            'Scala',
            'Scheme',
            'Shell Script',
            'Smalltalk',
            'Solidity',
            'SQL',
            'Swift',
            'TypeScript',
            'VBA',
            'Visual Basic',
            'WebAssembly',
            'Zig',
            'ABAP',
            'Apex',
            'ColdFusion',
            'DCL',
            'Eiffel',
            'Forth',
            'Hack',
            'J#',
            'JCL',
            'LabVIEW',
            'Ladder Logic',
            'MUMPS',
            'PL/SQL',
            'PostScript',
            'Q',
            'RPG',
            'SAS',
            'SPARK',
            'Tcl',
            'Verilog',
            'VHDL',
            'G-code',
            'HLSL',
            'GLSL',
            'OpenCL',
            'CUDA',
            'Maple',
            'Mathematica',
            'Max/MSP',
            'Pure Data',
            'SuperCollider',
            'ChucK',
            'Processing',
            'P5.js',
            'Logo',
            'Scratch',
            'Alice',
            'Piet',
            'Brainfuck',
            'Whitespace',
            'Malbolge',
            'REST API',
            'SOAP',
            'OAuth',
            'JWT',
            'WebSockets',
            'WebRTC',
            'Blockchain',
            'Smart Contracts',
            'Machine Learning',
            'Deep Learning',
            'Computer Vision',
            'NLP',
            'Data Science',
            'Big Data',
            'Hadoop',
            'Spark',
            'Kafka',
            'RabbitMQ',
            'SOLID Principles',
            'Design Patterns',
            'Problem Solving',
            'Algorithms',
            'Data Structures',
            'Cybersecurity',
            'Cryptography',
            'Ethical Hacking',
            'UI/UX Design',
            'Figma',
            'Adobe XD',
            'Sketch',
            'Photoshop',
            'Illustrator',
            'React Native',
            'Flutter',
            'Ionic',
            'NativeScript',
            'Xamarin',
            'Android SDK',
            'IOS',
            'SQL',
            'MySQL',
            'PostgreSQL',
            'SQL Server',
            'Oracle',
            'SQLite',
            'MongoDB',
            'Redis',
            'Cassandra',
            'Elasticsearch',
            'Firebase',
            'DynamoDB',
            'Neo4j',
            'Docker',
            'Kubernetes',
            'Terraform',
            'AWS',
            'Azure',
            'Google Cloud',
            'CI/CD',
            'Jenkins',
            'GitHub Actions',
            'GitLab CI',
            'Ansible',
            'Puppet',
            'Chef',
            'Nginx',
            'Apache',
            'Linux',
            'Bash',
            'PowerShell',
            'Git',
            'GitHub',
            'GitLab',
            'Bitbucket',
            'SVN',
            'SCRUM',
            'Kanban',
            'Agile',
            'Lean',
            'Extreme Programming',
            'TDD',
            'BDD',
            'DDD',
            'Clean Architecture',
            'Microservices',
            'Monolithic Architecture',
            'Serverless',
        ];

        foreach ($habilidades as $habilidade) {
            Habilidade::create(['nome' => $habilidade]);
        }
    }
}
